# Generated by Django 4.1.2 on 2023-01-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='steam_uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
