# Generated by Django 4.1.2 on 2023-01-11 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steam_api', '0003_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=255)),
                ('gid', models.IntegerField()),
            ],
            options={
                'ordering': ['game_name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=5000)),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steam_api.game')),
                ('steam_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steam_api.user')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
