# Generated by Django 4.1.2 on 2023-01-11 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam_api', '0005_gamer_alter_review_steam_uid_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='steam_uid',
        ),
    ]
