# Generated by Django 4.1.2 on 2022-10-19 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_alter_osoba_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Druzyna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('kraj', models.CharField(choices=[('PL', 'Polska'), ('DE', 'Niemcy'), ('US', 'Stany Zjednoczone')], default='PL', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Drużyny',
                'ordering': ['nazwa'],
            },
        ),
        migrations.AddField(
            model_name='osoba',
            name='druzyna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample.druzyna'),
        ),
    ]
